### PR TITLE
[Bug] Non-voluntary selections seem to duplicate

### LINKED ISSUE #185: [Bug] Non-voluntary selections seem to duplicate

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #185
image

image

### CODE REVIEW

File: app/controllers/account/benefits/enrollment/elect.js [hunk 1]
```diff
@@ -90,6 +107,8 @@ export default class AccountBenefitsEnrollmentElectController extends Controller
 
   @action
   async onCoverageChange (election) {
+    console.log('election', election)
+
```
Comment (James1x0) [inline app/controllers/account/benefits/enrollment/elect.js:111]:
```suggestion
```

**Review by James1x0 — APPROVED** [review]

File: app/controllers/account/benefits/enrollment/elect.js (hunk 1 above)
Comment (JavaLavaMT) [reply app/controllers/account/benefits/enrollment/elect.js]: 🤦‍♂️ thanks
