### PR TITLE
[Bug] Model for open enrollment needs start and end instead of just day/month

### LINKED ISSUE #112: Model for open enrollment needs start and end instead of just day/month

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #112
matched Granite model and serializer

### CODE REVIEW

File: app/models/open-enrollment.js [hunk 1]
```diff
@@ -1,10 +1,34 @@
...
+  @computed('end')
+  get endMonth () {
+    return Number(moment(this.end).format('M'));
+  }
+
+  @computed('end')
+  get endDay () {
+    return Number(moment(this.end).format('D'));
+  }
+}
```
Comment (James1x0) [inline app/models/open-enrollment.js:34]:
```suggestion
}

```

File: app/serializers/open-enrollment.js [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    };
+
+    json.end = {
+      month: end.getMonth() + 1,
+      day:   end.getDate()
+    };
+
+    return json;
+  }
+}
```
Comment (James1x0) [inline app/serializers/open-enrollment.js:33]:
```suggestion
}

```
