### PR TITLE
[Fix] Saving employee changes

### LINKED ISSUE #76: [Bug] Save employee changes button does nothing

### PR DESCRIPTION
**Pull request by petersonbrock**
closes #76 

middleName was missing from mutable attributes

### CODE REVIEW

File: app/controllers/account/information.js [hunk 1]
```diff
@@ -38,16 +38,19 @@ export default Controller.extend(ajaxStatus, {
           changes = [];
 
       for (let field in changedAttributes) {
-        if (!employeeMutableAttrs.includes(field)) {
-          return;
-        }
+        if (Object.prototype.hasOwnProperty.call(changedAttributes, field)) {
```
Comment (James1x0) [inline app/controllers/account/information.js]: Any reason for the prototype style invocation? Also just negate the logic..
```suggestion
        if (!changedAttributes.hasOwnProperty(field)) {
          continue;
        }
```
