### PR TITLE
[Bug] In benefits page, plan shows as disabled, it should match others

### LINKED ISSUE #182: [Bug] In benefits page, plan shows as disabled even though it should either be hidden or shown altogether

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #182

image

image

### CODE REVIEW

File: app/components/enrollment/plan-select-card.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ export default class EnrollmentPlanSelectCardComponent extends Component {
   get planClasses () {
     return [
       this.electionForPlan && 'enrollment__plan-select--is-elected',
-      this.disabled && 'enrollment__plan-select--disabled',
+      this.args.readOnly ? " " : this.disabled && 'enrollment__plan-select--disabled',
```
Comment (James1x0) [inline app/components/enrollment/plan-select-card.js:44]:
```suggestion
      this.args.readOnly ? false : this.disabled && 'enrollment__plan-select--disabled',
```
