### PR TITLE
[Bug] When editing or creating a dependent at the same time, duplicate id fields are created

### LINKED ISSUE #128: [Bug] When editing or creating a dependent at the same time, duplicate id fields are created

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #128

### CODE REVIEW

File: app/components/input/quick-form-input.js [hunk 1]
```diff
@@ -33,7 +33,11 @@ const QuickFormInputComponent = Component.extend({
   }),
 
   inputId: computed('elementId', 'computedClassName', function () {
-    return `${this.get('computedClassName')}__${this.get('elementId')}`;
+    return `${this.computedClassName}__${this.elementId}`;
+  }),
+
+  fieldId: computed('elementId', 'field.id', function () {
+    return `${this.get('field.id')}__${this.elementId}`;
```
Comment (James1x0) [inline app/components/input/quick-form-input.js:40]:
```
    return `${this.get('field.id')}__${this.elementId}`;
```
Can you provide a fallback if `field.id` isn't defined?

File: app/components/input/quick-form-input.js [hunk 2]
```diff
@@ -68,11 +72,11 @@ const QuickFormInputComponent = Component.extend({
     if (type === 'init') {
       $dropdown.attr({
         'aria-haspopup':   'listbox',
-        'aria-labelledby': `${this.get('inputId')}__text ${this.get('inputId')}__label`,
+        'aria-labelledby': `${tthis.inputId__text ${tthis.inputId__label`,
```
Comment (James1x0) [inline app/components/input/quick-form-input.js:75]: 👎

File: app/components/input/quick-form-input.js [hunk 3]
```diff
@@ -84,7 +88,7 @@ const QuickFormInputComponent = Component.extend({
         $menu.focus();
       }, 300);
     } else if (type === 'hide') {
-      if (this.get('adtIsFocusing')) {
+      if (tthis.adtIsFocusing {
```
Comment (James1x0) [inline app/components/input/quick-form-input.js:91]:
```suggestion
      if (this.adtIsFocusing) {
```

File: app/components/input/quick-form-input.js [hunk 4]
```diff
@@ -95,7 +99,7 @@ const QuickFormInputComponent = Component.extend({
 
         let totalFocusLoss = $focused.id && !this.$(`#${$focused.id}`)[0];
 
-        if (!this.get('adtIsFocusing') && !totalFocusLoss) {
+        if (!tthis.adtIsFocusing&& !totalFocusLoss) {
```
Comment (James1x0) [inline app/components/input/quick-form-input.js:102]:
```suggestion
        if (!this.adtIsFocusing && !totalFocusLoss) {
```

File: app/config/forms/benefits.js [hunk 5]
```diff
@@ -175,6 +176,7 @@ export const informationForm = [{
   path:        'employee.ssn',
   selectText:  'SSN',
   class:       'eight wide field',
+  id:          'HAHHAD',
```
Comment (James1x0) [inline app/config/forms/benefits.js:179]:
```
  id:          'HAHHAD',
```
😕

**Review by James1x0 — CHANGES_REQUESTED** [review]

**Review by James1x0 — APPROVED** [review]
After change to "for" and "id", we are good to merge.

File: app/components/input/quick-form-input.js [hunk 6]
```diff
@@ -33,7 +33,13 @@ const QuickFormInputComponent = Component.extend({
   }),
 
   inputId: computed('elementId', 'computedClassName', function () {
-    return `${this.get('computedClassName')}__${this.get('elementId')}`;
+    return `${this.get('computedClassName').replace(/\s/g, '-')}__${this.get('elementId')}`;
+  }),
+
+  fieldId: computed('elementId', 'field.id', function () {
+    if (this.get('field.id')){
+      return `${this.get('field.id').replace(/\s/g, '-') || this.get('field.label').replace(/\s/g, '-')}__${this.elementId}`;
```
Comment (James1x0) [inline app/components/input/quick-form-input.js:41]:
```suggestion
      return `${this.get('field.id') ? this.get('field.id').replace(/\s/g, '-') : (this.get('field.label') || '').replace(/\s/g, '-')}__${this.elementId}`;
```

Comment (James1x0) [reply app/components/input/quick-form-input.js:41]: Safety 1st 🥽
