### PR TITLE
[Bug] If you begin an enrollment then refresh the page on any step, a new one is created

### LINKED ISSUE #120: [Bug] If you begin an enrollment then refresh the page on any step, a new one is created

### PR DESCRIPTION
**Pull request by JavaLavaMT**
closes #120

### CODE REVIEW

**Review by James1x0 — APPROVED** [review]

File: app/routes/account/benefits/enrollment.js [hunk 1]
```diff
@@ -48,9 +48,18 @@ export default class AccountBenefitsEnrollmentRoute extends GraniteWizardRoute {
 
   async model (params) {
     if (!params.enrollment) {
-      return await this.store.createRecord('enrollment', {
-        employee: this.auth.user,
-        company:  this.auth.user.get('company')
+      const employee = await this.auth.userId;
+
+      let enrollment = await this.store.queryRecord('enrollment', {
+        employee,
```
Comment (James1x0) [inline app/routes/account/benefits/enrollment.js:54]:
```suggestion
```

Comment (James1x0) [reply app/routes/account/benefits/enrollment.js:54]: This is redundant
